# Generated by Django 2.2 on 2021-01-21 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210120_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=100, verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 9, 52, 730861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'Ж')], max_length=1, verbose_name='пол'),
        ),
    ]
