# Generated by Django 2.2 on 2021-01-21 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210121_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='avatar_url',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 13, 52, 818186, tzinfo=utc)),
        ),
    ]
