# Generated by Django 2.2 on 2021-01-23 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210123_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='url',
            field=models.URLField(blank=True, max_length=100, verbose_name='адрес личной страницы в VK'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 14, 53, 2, 391473, tzinfo=utc)),
        ),
    ]
